CREATE OR REPLACE TRIGGER EVENT_DUTIES_ASS_TRG BEFORE
    INSERT OR UPDATE ON EVENT_DUTIES_ASS FOR EACH ROW
BEGIN
    IF :NEW.ASSIGNMENT_END_DATE IS NOT NULL AND :NEW.ASSIGNMENT_END_DATE <= SYSDATE THEN
        RAISE EXCEPTIONS_PKG.ASSIGMENT_DATE_EXC;
    END IF;
EXCEPTION
    WHEN EXCEPTIONS_PKG.ASSIGMENT_DATE_EXC THEN
        DBMS_OUTPUT.PUT_LINE('An error was encountered - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
END;