--TODO: TRIGGER FOR RANK INSERTION (LOG)
CREATE OR REPLACE TRIGGER MEMBER_PROMOTION_LOG AFTER INSERT ON RANK_PRIVILEGES
BEGIN

END;
/
CREATE OR REPLACE TRIGGER MEMBER_PROMOTION_LOG AFTER
    UPDATE ON RANK_PRIVILEGES
BEGIN
END;
/
CREATE OR REPLACE TRIGGER MEMBER_PROMOTION_LOG AFTER
    DELETE ON RANK_PRIVILEGES
BEGIN
END;
/
CREATE OR REPLACE TRIGGER RANK_INSERTION_LOG AFTER INSERT ON RANK_DICTIONARY
BEGIN
END;
/
--TODO: TRIGGER FOR GATHERING REPORT INSERTION (LOG)