CREATE OR REPLACE VIEW MEMBERS_RANK_VW AS
    SELECT MEMBER_ID,
        M.FIRST_NAME || ' ' || M.LAST_NAME                        AS MEMBER_NAME,
        LISTAGG(RD.RANK_NAME, ';') WITHIN GROUP (ORDER BY RD.RANK_NAME) AS ALL_RANKS
    FROM RANK_PRIVILEGES RP
        INNER JOIN MEMBERS M
        USING (MEMBER_ID)
        INNER JOIN RANK_DICTIONARY RD
        USING (RANK_ID)
    GROUP BY MEMBER_ID,
        M.FIRST_NAME,
        M.LAST_NAME;