-- Unix/Linux
-- CREATE OR REPLACE DIRECTORY FILES_FOR_REPORT AS '&ORACLE_BASE/reports/temp';
-- Windows
-- CREATE OR REPLACE DIRECTORY FILES_FOR_REPORT AS '%ORACLE_HOME%\reports\temp';

CREATE OR REPLACE DIRECTORY 'FILES_FOR_REPORT' AS '/db2_hrphee/temp';

GRANT READ, WRITE ON DIRECTORY FILES_FOR_REPORT TO PUBLIC;