CONNECT CSERKESZ_ADMIN/12345678@XE_LOCAL;

DELETE FROM RANK_DICTIONARY;

SELECT *
FROM ORS;
SELECT * FROM PATROL;
SELECT *
FROM MEMBERS;

SELECT *
FROM ADDRESS;

SELECT *
FROM MEMBERS_RANK_VW;

DECLARE
    V_RANK_NAME RANK_DICTIONARY.RANK_NAME%TYPE;
BEGIN
V_RANK_NAME := CONSTANTS_PKG.RANKS_NAMES ( 'GL' );
    CONSTANTS_PKG.INIT_RANKS;
    DBMS_OUTPUT.PUT_LINE ( '-------' );
    DBMS_OUTPUT.PUT_LINE ( V_RANK_NAME );
END;
/

