CREATE SEQUENCE REPORTS_SEQ 
START WITH 1300
INCREMENT BY 1;

CREATE SEQUENCE MEMBERS_SEQ
START WITH 140
INCREMENT BY 1;

CREATE SEQUENCE ADDRES_SEQ
START WITH 10
INCREMENT BY 1;

CREATE SEQUENCE ORS_PATROL_SEQ
START WITH 166
INCREMENT BY 1;

CREATE SEQUENCE POSTS_SEQ
START WITH 1350
INCREMENT BY 1;

CREATE SEQUENCE KNOWLEDGE_MEDIA_SEQ
START WITH 1300
INCREMENT BY 1;