CREATE SEQUENCE REPORTS_SEQ
START WITH 1300
INCREMENT BY 1;

CREATE SEQUENCE MEMBERS_SEQ
START WITH 140
INCREMENT BY 1;

CREATE SEQUENCE ADDRESS_SEQ
START WITH 10
INCREMENT BY 1;

CREATE SEQUENCE ORS_PATROL_SEQ
START WITH 166
INCREMENT BY 1;

CREATE SEQUENCE POSTS_SEQ
START WITH 1350
INCREMENT BY 1;

-- CREATE SEQUENCE KNOWLEDGE_MEDIA_SEQ
-- START WITH 1300
-- INCREMENT BY 1;

CREATE SEQUENCE RANKS_SEQ
START WITH 4450 
INCREMENT BY 1;

CREATE SEQUENCE HISTORY_SEQ
START WITH 6700
INCREMENT BY 1;

CREATE SEQUENCE DUTY_SEQ
START WITH 6800
INCREMENT BY 1;