CREATE OR REPLACE TABLE ORS (
    ORS_ID NUMBER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PATROL_ID NUMBER NOT NULL,
);

ALTER TABLE ORS
    ADD CONSTRAINT ORS_PATROL_FK FOREIGN KEY (
        PATROL_ID
    )
        REFERENCES PATROL(
            PATROL_ID
        );

CREATE OR REPLACE TABLE PATROL (
    PATROL_ID NUMBER PRIMARY KEY,
    PATROL_NAME VARCHAR2(100) NOT NULL
);