CREATE OR REPLACE TABLE POSTS (
    POST_ID NUMBER PRIMARY KEY,
    POST_NAME VARCHAR2(100) NOT NULL,
    POST_DESCRIPTION VARCHAR2(2000),
    POST_TYPE VARCHAR2(4) NOT NULL, -- ['NEWS', 'BLOG', 'KNOW']
);