-- DYNAMIC SQL FOR CREATE GROUP_LEADER
CREATE USER {LAST_NAME}_LEADER IDENTIFIED BY PASSWORD {PSSWRD} DEFAULT TABLESPACE USER QUOTA UNLIMITED ON USER;

GRANT CREATE SESSION TO {LAST_NAME}_LEADER;

GRANT SELECT ON ORS, EVENTS, EVENT_DUTIES_ASS, DUTIES, KNOWLEDGE, KNOWLEDGE_MEDIA_ASS, MEDIA TO {LAST_NAME}_LEADER;
GRANT UPDATE ON MEMBERS to {LAST_NAME}_LEADER;