CREATE OR REPLACE PACKAGE EXCEPTIONS_PKG IS
    INVALID_FORMAT EXCEPTION;
    PRAGMA EXCEPTION_INIT (INVALID_FORMAT, -20001);
END EXCEPTIONS_PKG;
/

CREATE OR REPLACE PACKAGE BODY EXCEPTIONS_PKG IS
END EXCEPTIONS_PKG;
/